### ISSUE TITLE
Google Maps For Android SDK could not display MapView on AAOS Emulator

### ISSUE THREAD

**Issue by ymc961** [googlemaps-samples/android-samples#1084]
Google Maps For Android SDK could not display MapView on AAOS Emulator.

I use my google map API_KEY in [the demo](https://github.com/googlemaps/android-samples.git). The MapView Can display on my tablet. but it can't display on AAOS Emulator. 

The AAOS Emulator has google maps an google play service.

1. on the AAOS Emulator
<img width="564" alt="image" src="https://user-images.githubusercontent.com/60420282/201013190-190adc1f-da77-4754-9e40-d15b46e525fc.png">
<img width="573" alt="image" src="https://user-images.githubusercontent.com/60420282/201013058-03dc68b1-5d1c-4ca1-bb31-fde987921cb2.png">

2. on the tablet
![image](https://user-images.githubusercontent.com/60420282/201013607-bb2f51c9-b06b-4d65-a961-6c34253bab69.png)

**Comment by ymc961** [comment]
<img width="582" alt="image" src="https://user-images.githubusercontent.com/60420282/201014016-6a1f99f3-8823-45d4-809b-2073b038195f.png">

**Comment by kikoso** [comment]
Hi @ymc961. Which emulator image are you using?

Can you check that you are using the latest image available via Android Studio Canary? Could you also try the following steps?

Settings > Apps & Notifications > App > Google Play Services > Storage
Click Clear Cache
Manage Space > Clear all data

**Comment by dkhawk** [comment]
Stale issue
