### ISSUE TITLE
snippet-bot full scan

### ISSUE THREAD

**Issue by wangela** [googlemaps-samples/android-samples#1354]
## snippet-bot scan result
Life is too short to manually check unmatched region tags.
Here is the result:
- [ ] [snippets/app/src/gms/java/com/google/maps/example/kotlin/GroundOverlays.kt:48](https://github.com/googlemaps-samples/android-samples/blob/ff1b2de/snippets/app/src/gms/java/com/google/maps/example/kotlin/GroundOverlays.kt#L48), tag `maps_android_ground_overlays_remove` doesn't have a matching start tag.
- [ ] [snippets/app/src/gms/java/com/google/maps/example/kotlin/GroundOverlays.kt:50](https://github.com/googlemaps-samples/android-samples/blob/ff1b2de/snippets/app/src/gms/java/com/google/maps/example/kotlin/GroundOverlays.kt#L50), tag `maps_android_ground_overlays_change_image` already started.

---
Report generated by [snippet-bot](https://github.com/apps/snippet-bot).
If you find problems with this result, please file an issue at:
https://github.com/googleapis/repo-automation-bots/issues.

**Comment by dkhawk** [comment]
No longer broken.
