### ISSUE TITLE
APK published in Releases doesn't display a map

### ISSUE THREAD

**Issue by julenka** [googlemaps-samples/android-samples#1592]
Thanks for stopping by to let us know something could be better!

---

Please be sure to include as much information as possible:

#### Environment details

1. I am testing on an Samsung Galaxy S10+ Andoid version 12

#### Steps to reproduce
1. Download the V1.10.1 release at https://github.com/googlemaps-samples/android-samples/releases
2. ADB install the apk onto my device
3. Run the sample app and open the "Basic Map" view.

Expected: I see a Google map show up

Actual: The map is all gray

I think this is happening because the samples available in releases don't have an API key associated with them. Are there instructions about how to insert an API key into the sample APKs available from the releases page? I was hoping to try a sample without needing to clone the repo and build the APK myself.

**Comment by dkhawk** [comment]
You will need an API key.  Please see the instructions for the quick start here: https://developers.google.com/maps/documentation/android-sdk/start

And specifically here: https://developers.google.com/maps/documentation/android-sdk/start#get-key
